const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Starting deployment of DocumentRegistry...");

  // 1. Get the Contract Factory and deploy
  const DocumentRegistry = await hre.ethers.getContractFactory("DocumentRegistry");
  const documentRegistry = await DocumentRegistry.deploy();

  // Wait for the deployment transaction to be confirmed
  await documentRegistry.waitForDeployment();
  const contractAddress = await documentRegistry.getAddress();

  console.log(`DocumentRegistry successfully deployed to: ${contractAddress}`);

  // 2. Export the ABI and Contract Address to the frontend
  exportToFrontend(contractAddress);
}

function exportToFrontend(contractAddress) {
  // Define the target path in the frontend React app
  const frontendContractsDir = path.join(__dirname, "..", "..", "frontend", "src", "contracts");

  // Create the src/contracts directory if it doesn't exist
  if (!fs.existsSync(frontendContractsDir)) {
    fs.mkdirSync(frontendContractsDir, { recursive: true });
  }

  // Locate the compiled ABI generated by Hardhat
  const artifactPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "DocumentRegistry.sol",
    "DocumentRegistry.json"
  );

  if (!fs.existsSync(artifactPath)) {
    console.error("Error: Artifact not found. Ensure the contract is compiled.");
    return;
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));

  // Package the deployed address and ABI together
  const contractData = {
    address: contractAddress,
    abi: artifact.abi,
  };

  const outputPath = path.join(frontendContractsDir, "DocumentRegistry.json");

  // Save directly to the frontend directory
  fs.writeFileSync(
    outputPath,
    JSON.stringify(contractData, null, 2)
  );

  console.log(`Contract Address and ABI successfully exported to ${outputPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
